build_and_store_wheels: &BUILD_AND_STORE_WHEELS
  install_cibuildwheel_script:
    - python -m pip install cibuildwheel==2.17.0
    - curl -o /tmp/Python38.pkg https://www.python.org/ftp/python/3.8.10/python-3.8.10-macos11.pkg
    - sudo installer -pkg /tmp/Python38.pkg -target /
    - sh "/Applications/Python 3.8/Install Certificates.command"
  run_cibuildwheel_script:
    - cibuildwheel
  wheels_artifacts:
    path: "wheelhouse/*"

macos_arm64_task:
  name: Build macOS arm64 wheels.
  macos_instance:
    image: ghcr.io/cirruslabs/macos-sonoma-xcode
  env:
    PATH: /opt/homebrew/opt/python@3.10/libexec/bin:$PATH
    matrix:
      - CIBW_BUILD: "cp38-macosx_arm64"
      - CIBW_BUILD: "cp39-macosx_arm64"
      - CIBW_BUILD: "cp310-macosx_arm64"
      - CIBW_BUILD: "cp311-macosx_arm64"
      - CIBW_BUILD: "cp312-macosx_arm64"
    CIBW_ARCHS: arm64
  install_pre_requirements_script:
    - brew install python@3.10
  <<: *BUILD_AND_STORE_WHEELS
