FROM quay.io/pypa/manylinux_2_24_x86_64

RUN echo "deb http://deb.debian.org/debian stretch-backports main" >> /etc/apt/sources.list &&\
  apt-get update &&\
  apt-get install -y --no-install-recommends \
  build-essential\
  cmake\
  sqlite3\
  libsqlite3-dev\
  zlib1g-dev\
  swig\
  libeigen3-dev\
  git\
  wget\
  zip\
  unzip\
  patchelf\
  ninja-build\
  libfreetype6-dev &&\
  apt-get clean -y

WORKDIR /
