FROM quay.io/pypa/manylinux2014_x86_64

RUN yum -y install epel-release &&\
    yum install -y \
    tk-devel\
    readline-devel\
    zlib-devel\
    bzip2-devel\
    sqlite-devel\
    @development\
    eigen3-devel\
    swig\
    git\
    wget\
    zip\
    unzip\
    cmake3\
    ninja-build\
    libpng12-devel\
    pixman-devel\
    freetype-devel &&\
    yum clean all &&\
    rm -rf /var/cache/yum


WORKDIR /
