version: 2.1

jobs:
  linux-arm64-wheels:
    working_directory: ~/linux-wheels
    machine:
      image: ubuntu-2004:current
      resource_class: arm.large
    parameters:
      python-version:
        type: string
    steps:
      - checkout
      - run:
          name: Build the ARM64 wheels on linux
          environment:
            CIBW_BUILD: cp<< parameters.python-version >>-manylinux_aarch64
            CIBW_ARCHS: aarch64

          command: |
            python3 -m pip install cibuildwheel==2.21.3
            python3 -m cibuildwheel --output-dir wheelhouse
      - store_artifacts:
          path: wheelhouse/

  # osx-wheels:
  #   working_directory: ~/osx-wheels
  #   macos:
  #     xcode: 15.4.0
  #   resource_class: macos.m1.medium.gen1
  #   parameters:
  #     python-version:
  #       type: string
  #   steps:
  #     - checkout
  #     - run:
  #         name: Build the OS X wheels.
  #         environment:
  #           CIBW_BUILD: cp<< parameters.python-version >>-macosx_arm64

  #         command: |
  #           pip3 install cibuildwheel==2.17.0
  #           cibuildwheel --output-dir wheelhouse
  #     - store_artifacts:
  #         path: wheelhouse/


workflows:
  all-tests:
    jobs:
      - linux-arm64-wheels:
          matrix:
            parameters:
              python-version: ["39", "310", "311", "312", "313"]
      # - osx-wheels:
      #     matrix:
      #       parameters:
      #         python-version: ["38", "39", "310", "311", "312"]

