version: 2.1

jobs:
  linux-arm64-wheels:
    working_directory: ~/linux-wheels
    machine:
      image: ubuntu-2004:202101-01
      resource_class: arm.medium
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build the ARM64 wheels on linux
          environment:
            CIBW_BUILD: cp38-manylinux_aarch64
            CIBW_ARCHS: aarch64
            CIBW_MANYLINUX_X86_64_IMAGE: manylinux2014
            CIBW_MANYLINUX_I686_IMAGE: manylinux2014

          command: |
            python -m pip install cibuildwheel==2.3.1
            python -m cibuildwheel --output-dir wheelhouse
      - store_artifacts:
          path: wheelhouse/

workflows:
  all-tests:
    jobs:
      - linux-arm64-wheels
