name: Nightly check for new RDKit tags
on:
  push:
  # schedule:
    # https://crontab.guru/every-night-at-midnight
    # - cron: "0 0 * * *"

jobs:
  update_tag:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Check out RDKit repo
        uses: actions/checkout@master
        with:
          repository: rdkit/rdkit
          path: rdkit

      - name: Get most tags and compare
        id: tags
        run: |
          current_tag=$(grep rdkit_tag setup.py | head -1 | xargs -n 1 | tail -1)
          cd rdkit
          new_tag=$(git describe --tags `git rev-list --tags --max-count=1`)
          cd ..
          rm -fr rdkit
          echo ::set-output name=changed::false
          if [[ "$new_tag" != "$current_tag ]]; then
          sed -i "s/rdkit_tag =.*/rdkit_tag = \"$new_tag\"/g" setup.py
          echo ::set-output name=changed::true
          echo ::set-output name=new_tag::${new_tag}
          fi

      - name: Create Pull Request
        if: ${{ steps.tags.outputs.changed }}
        uses: gr2m/create-or-update-pull-request-action@v1.x
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          title: "Bump RDKit to ${{ steps.tags.outputs.new_tag }}"
          branch: "bump-rdkit-${{ steps.tags.outputs.new_tag }}"
          path: "./"
          commit-message: "Bump RDKit to ${{ steps.tags.outputs.new_tag }}"
